chocolate_shop/chocolate_app/urls.py
from django.urls import path
from . import views
app_name='chocolate_app'

urlpatterns = [
    path('',views.home,name='home'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('shop',views.shop,name='shop'),
    path('confirm', views.confirm, name='confirm'),

]

chocolate_shop/chocolate_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chocolate_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chocolate_shop/chocolate_app/models.py
from django.db import models

# Create your models here.
class Customer_details(models.Model):
    customer_name=models.CharField(max_length=250)
    phone_no=models.CharField(max_length=250)
    email=models.EmailField(max_length=250)
    address = models.TextField()
    district = models.CharField(max_length=250)
    city = models.CharField(max_length=250)
    chocolate = models.CharField(max_length=250)
    price = models.CharField(max_length=250)
    quantity = models.IntegerField()

    def __str__(self):
        return '{}'.format(self.customer_name)

chocolate_shop/chocolate_app/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Customer_details

# Create your views here.
def home(request):
    return render(request,'home.html')


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['cpassword']

        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username already used")
                return redirect('chocolate_app:register')
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save();
                return redirect('chocolate_app:login')

        else:
            messages.info(request,"password doesn't match")
            return redirect('chocolate_app:register')


    return render(request,'register.html')


def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('chocolate_app:shop')
        else:
            messages.info(request,"invalid username or password")
            return redirect('chocolate_app:login')
    return render(request,'login.html')


def logout(request):
    auth.logout(request)
    return redirect('chocolate_app:home')

def shop(request):
    return render(request,'shop.html')


def confirm(request):
    if request.method == 'POST':
        customer_name=request.POST['customer_name']
        phone_no = request.POST['phone_no']
        email = request.POST['email']
        address = request.POST['address']
        district = request.POST['district']
        city = request.POST['city']
        chocolate = request.POST['chocolate']
        price = request.POST['price']
        quantity = request.POST['quantity']
        data=Customer_details(customer_name=customer_name,phone_no=phone_no,email=email,address=address,district=district,city=city,chocolate=chocolate,price=price,quantity=quantity)
        data.save();
        if data:
            messages.info(request,"success")
    return render(request,'confirm.html')

chocolate_shop/templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm</title>
<style>
body{
  font-family: Calibri, Helvetica, sans-serif;
}
.container {
    padding: 50px;
    background-color: grey;
    width:300px;
    margin:80px;
}

input[type=text], input[type=email], input[type=number]{
  width: 300px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
select{
  width: 130px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;

 }
input[type=text]:focus, input[type=email], input[type=number], select:focus {
  outline: none;
}
 div {
            padding: 10px 0;
         }
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 125px;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}

</style>
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <form method="post" action="{% url 'chocolate_app:confirm' %}">
        {% csrf_token %}

        <center>
        <div class="container">
            <h1>Confirm Order</h1>
            <input type="text" name="customer_name" placeholder= "Customer Name" size="15" required /><br>
            <input type="text" name="phone_no" placeholder="Phone Number" size="15" required /><br>
            <input type="email" name="email" placeholder="Email" size="15"required /><br>
            <input type="text" name="address" placeholder="Address" size="15"required /><br>
            <select id="inputDistrict" name="district" required>
                <option value="">Select District</option>
                <option value="Kannur">Kannur</option>
                <option value="Kochi">Kochi</option>
                <option value="Kasaragode">Kasaragode</option>
            </select>
            <select id="inputCity" name="city" required>
                <option value="">Select City</option>
            </select>
            <select id="chocolatename" name="chocolate" required>
                <option value="">Select Chocolate</option>
                <option value="Snickers">Snickers</option>
                <option value="Toblerone">Toblerone</option>
                <option value="Kitkat">Kitkat</option>
            </select>
            <select id="price" name="price" required>
                <option value="">Price</option>
            </select>
            <input type="number" name="quantity" placeholder="Quantity" size="15"required /><br>
            <input type="reset" class="registerbtn" value="Reset">
            <input type="submit" class="registerbtn" value="Confirm"><br>
            <a href="{% url 'chocolate_app:logout' %}">Logout</a>
        </div>
        </center>
    </form>
    <script>
        var Kannur = ["Payyanur","Puthyatheru","Kambil",];
        var  Kochi= ["Ottapalam", "Fort Kochi", "Marian Drive"];
        var  Kasaragode= ["Cheruvathur","Ranipuram","Neleswaram"];
        $("#inputDistrict").change(function () {
               var StateSelected = $(this).val();
               var optionsList;
               var htmlString = "";

              switch (StateSelected) {
              case "Kannur":
                optionsList = Kannur;
                break;
              case "Kochi":
                optionsList = Kochi;
                break;
              case "Kasaragode":
                optionsList = Kasaragode;
                break;
              }

              for (var i = 0; i < optionsList.length; i++) {
                htmlString =
                htmlString +
                "<option value='" +
                optionsList[i] +
                "'>" +
                optionsList[i] +
                "</option>";
              }
              $("#inputCity").html(htmlString);
        });
    </script>
    <script>
        var Snickers = ["40","50","60",];
        var  Toblerone= ["70", "80", "90"];
        var  Kitkat= ["100","110","120"];
        $("#chocolatename").change(function () {
               var StateSelected = $(this).val();
               var optionsList;
               var htmlString = "";

              switch (StateSelected) {
              case "Snickers":
                optionsList = Snickers;
                break;
              case "Toblerone":
                optionsList = Toblerone;
                break;
              case "Kitkat":
                optionsList = Kitkat;
                break;
              }

              for (var i = 0; i < optionsList.length; i++) {
                htmlString =
                htmlString +
                "<option value='" +
                optionsList[i] +
                "'>" +
                optionsList[i] +
                "</option>";
              }
              $("#price").html(htmlString);
        });
    </script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
                {% if messages %}
                swal({
                    title:"Success",
                    text:"Order Placed",
                    icon:"success",
                }).then(function(){
                    window.location="{% url 'chocolate_app:shop' %}";
                {% endif %}
               });
         });
    </script>
</body>
</html>

chocolate_shop/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Chocolux-Online Shop </title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout inner_posituong computer_page">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="{% url 'chocolate_app:home' %}"><img src="{% static 'images/logo1.PNG' %}" alt="#"  height="80px" width="80px"/></a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'chocolate_app:home' %}">Home</a>
                              </li>
                              <li class="nav-item dropdown">
                                 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Branch</a>
                                 <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kasaragod_district">Kasaragod</a>
                                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur_district">Kannur</a>
                                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode_district">Kozhikode</a>
                                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/malappuram_district">Malappuram</a>
                                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kochi_district">Kochi</a>
                                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur_district">Thrissur</a>
                                    <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvanathapuram_district">Thiruvanathapuram</a>
                                 </div>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'chocolate_app:register' %}">Register</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'chocolate_app:login' %}">Login</a>
                              </li>
                           </ul>
                        </div>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header inner -->
      <!-- end header -->
      <!-- about section -->
      <div class="about">
         <div class="container">
            <div class="row d_flex">
               <div class="col-md-5">
                  <div class="titlepage">
                     <h2>About Us</h2>
                     <p>Homemade chocolates are chocolates that are made from the home and not in a factory of some sort where mass production of chocolates is produced with a short period of time. Those who are into homemade chocolate retail businesses ensure that they target locations where they can easily attract children because children are the major consumers of products such as homemade chocolates and candies.</p>
                     <a class="read_more" href="{% url 'chocolate_app:login' %}">Shop Now</a>
                  </div>
               </div>
               <div class="col-md-7">
                  <div class="about_img">
                     <figure><img src="{% static 'images/about1.png' %}" alt="#" height="200px" width="400px"/></figure>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </div>
      <!-- end about section -->
      <!--  footer -->
      <footer>
         <div class="footer">
            <div class="container">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                     <ul class="social_icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
                  <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                     <h3>Contact Us</h3>
                     <ul class="conta">
                        <li>Chocolux-Online Shop<br> Near Caltex<br> Kannur <br>Kerala <br><i class="fa fa-phone" aria-hidden="true">  987654321</i></li>
                     </ul>
                  </div>

               </div>
            </div>
            <div class="copyright">
               <div class="container">
                  <div class="row">
                     <div class="col-md-12">
                        <p>© 2019 All Rights Reserved. Chocolux-Online Shop</a></p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
   </body>
</html>

chocolate_shop/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
<style>
body{
  font-family: Calibri, Helvetica, sans-serif;
}
.container {
    padding: 50px;
    background-color: grey;
    width:300px;
    margin:80px;
}

input[type=text], input[type=password] {
  width: 300px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
input[type=text]:focus, input[type=password]:focus {
  outline: none;
}
 div {
            padding: 10px 0;
         }
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 325px;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}

</style>
</head>
<body>
    <form method="post" action="{% url 'chocolate_app:login' %}">
        {% csrf_token %}
        <center>
        <div class="container">
            <h1>Sign in</h1>
            <input type="text" name="username" placeholder= "Username" size="15" required /><br>
            <input type="password" name="password" placeholder="Password" size="15" required /><br>
            <input type="submit" class="registerbtn" value="Login"><br>
            {% for msg in messages %}
                <h4 style="color:red">{{msg}}</h4>
            {% endfor %}
            <p>Not Registered? please</p><a href="{% url 'chocolate_app:register' %}"> Sign up</a>

        </div>
        </center>
    </form>
</body>
</html>

chocolate_shop/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
<style>
body{
  font-family: Calibri, Helvetica, sans-serif;
}
.container {
    padding: 50px;
    background-color: grey;
    width:300px;
    margin:80px;
}

input[type=text], input[type=password] {
  width: 300px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
input[type=text]:focus, input[type=password]:focus {
  outline: none;
}
 div {
            padding: 10px 0;
         }
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 125px;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}

</style>
</head>
<body>
    <form method="post" action="{% url 'chocolate_app:register' %}">
        {% csrf_token %}

        <center>
        <div class="container">
            {% for msg in messages %}
                <h4 style="color:red">{{msg}}</h4>
            {% endfor %}
            <h1>Sign Up</h1>
            <input type="text" name="username" placeholder= "Username" size="15" required /><br>
            <input type="password" name="password" placeholder="Password" size="15" required /><br>
            <input type="password" name="cpassword" placeholder="Confirm Password" size="15"required /><br>
            <input type="reset" class="registerbtn" value="Reset">
            <input type="submit" class="registerbtn" value="Register"><br>
            <p>Already Registered? please</p><a href="{% url 'chocolate_app:login' %}"> Sign in</a>
        </div>
        </center>
    </form>
</body>
</html>

chocolate_shop/templates/shop.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Chocolux-Online Shop </title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout inner_posituong computer_page">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="{% url 'chocolate_app:home' %}"><img src="{% static 'images/logo1.PNG' %}" alt="#"  height="80px" width="80px"/></a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'chocolate_app:shop' %}">{{user.username}}</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'chocolate_app:logout' %}">Logout</a>
                              </li>
                           </ul>
                        </div>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header inner -->
      <!-- end header -->
      <!-- about section -->
      <div class="about">
         <div class="container">
            <div class="row d_flex">
               <div class="col-md-5">
                  <div class="titlepage">
                     <h2>About Us</h2>
                     <p>Homemade chocolates are chocolates that are made from the home and not in a factory of some sort where mass production of chocolates is produced with a short period of time. Those who are into homemade chocolate retail businesses ensure that they target locations where they can easily attract children because children are the major consumers of products such as homemade chocolates and candies.</p>
                     <a class="read_more" href="{% url 'chocolate_app:confirm' %}">Chocolate Shopping</a>
                  </div>
               </div>
               <div class="col-md-7">
                  <div class="about_img">
                     <figure><img src="{% static 'images/about1.png' %}" alt="#" height="200px" width="400px"/></figure>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </div>
      <!-- end about section -->
      <!--  footer -->
      <footer>
         <div class="footer">
            <div class="container">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                     <ul class="social_icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
                  <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                     <h3>Contact Us</h3>
                     <ul class="conta">
                        <li>Chocolux-Online Shop<br> Near Caltex<br> Kannur <br>Kerala <br><i class="fa fa-phone" aria-hidden="true">  987654321</i></li>
                     </ul>
                  </div>

               </div>
            </div>
            <div class="copyright">
               <div class="container">
                  <div class="row">
                     <div class="col-md-12">
                        <p>© 2019 All Rights Reserved. Chocolux-Online Shop</a></p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
   </body>
</html>

</title>
</head>
<body>

</body>
</html>